name: Build Example

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          cd example && yarn install
      - name: Build Android Release
        run: |
          cd example/android && ./gradlew assembleDebug
